### ISSUE TITLE
Save the state of the log window (open/closed) 

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#20]
It would be great if somebody can add a script that remembers the log window state (opened/cosed).

**Comment by NightHawk32** [comment]
@skaman82 Did this, the problem is that I already have a fork of the configurator in my own repo. So this could result in some chaos. What do you prefer? Should I commit it to the ConfiguratorReworkTeam?

**Comment by skaman82** [comment]
Wow! Thanks! You can commit this to my new_stuff branch or make a direct PR to hydras origin developer branch. I am still sorting out if the ReworkTeam is actually a good idea :)

**Comment by NightHawk32** [comment]
Just tried that, but I have no write access to your repo. What are your concerns about the ReworkTeam?

**Comment by skaman82** [comment]
Then give me a PR to my new_suff branch. My concerns are not about the team itself. They are about working on multiple branches actually :) I try to find a way to coordinate the work efficiently and make it transparent who is working on what to eliminate duplicate work. If you have a idea a I am open for suggestions.

**Comment by NightHawk32** [comment]
So I have no other way than deleting my fork of the configurator, since github does not allow to fork multiple forks of a repo. Sometimes this is just annoying :).
I think the way you use the issue tracke is pretty good, so everyone knows about the open tasks and the details. If you collect all the changes in your repo you have the overview over all the changes. So I would just continue the way it is at the moment.

**Comment by skaman82** [comment]
This is merged now. Thanks @NightHawk32
