### ISSUE TITLE
Small rendering issue in landing tab

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#27]
Just noticed a rendering issue in the landing tab. This happens when the app window is small and the log is open. If you have to scroll to see the sponsors this happens:
<img width="1023" alt="bildschirmfoto 2015-11-09 um 14 57 58" src="https://cloud.githubusercontent.com/assets/11768024/11035378/667529ae-86f2-11e5-9543-94f8a99a78c9.png">
 @wanderzell do you have a clue why this happens?

**Comment by wanderzell** [comment]
![screen shot 2015-11-09 at 16 16 12](https://cloud.githubusercontent.com/assets/4578152/11035817/64570bbe-86fd-11e5-8569-8c792e3b1233.png)

I have entire sponsors section missing when log is open. I can check this later today.

**Comment by wanderzell** [comment]
@skaman82 
* Regarding sponsors background, if you decide to colour this please test this carefully. Primary reason why I changed it white was that solved the rendering problem. I am sure the colour itself is not root cause of this and it could be applied differently but it seemed just easiest (and for me personally also the prettiest) solution to leave it white.
* Regarding the sponsors links not clickable - I will take a look.

**Comment by skaman82** [comment]
Regarding the colors: It is a matter of personal taste like it is always is with design. The changelog bar being white now, I think both areas should't be white. There has to be a optical separation between the sponsors section. IMO the green bar isn't enough.

**Comment by skaman82** [comment]
this is fixed now thanks to @wanderzell
